package com.packtpub.springsecurity;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class HomeView extends CustomComponent {
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout footerLayout;

	@AutoGenerated
	private Label copyRight;

	@AutoGenerated
	private HorizontalLayout bodyLayout;

	@AutoGenerated
	private Label label_1;

	@AutoGenerated
	private HorizontalLayout headerLayout;

	@AutoGenerated
	private Button buttonLogout;

	@AutoGenerated
	private Button buttonChangePassword;

	@AutoGenerated
	private Label caption;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static Logger log = LoggerFactory.getLogger(HomeView.class);

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = -1768109717337479805L;
	
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HomeView() {
		log.trace("Initializing HomeView");
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public Button getButtonLogout() {
		return buttonLogout;
	}
	
	public Button getChangePasswordButton(){
		return buttonChangePassword;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setCaption("Home Window");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// headerLayout
		headerLayout = buildHeaderLayout();
		mainLayout.addComponent(headerLayout);
		
		// bodyLayout
		bodyLayout = buildBodyLayout();
		mainLayout.addComponent(bodyLayout);
		mainLayout.setExpandRatio(bodyLayout, 1.0f);
		
		// footerLayout
		footerLayout = buildFooterLayout();
		mainLayout.addComponent(footerLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHeaderLayout() {
		// common part: create layout
		headerLayout = new HorizontalLayout();
		headerLayout.setImmediate(false);
		headerLayout.setWidth("100.0%");
		headerLayout.setHeight("-1px");
		headerLayout.setMargin(true);
		headerLayout.setSpacing(true);
		
		// caption
		caption = new Label();
		caption.setImmediate(false);
		caption.setWidth("-1px");
		caption.setHeight("-1px");
		caption.setValue("Home Window");
		caption.setContentMode(3);
		headerLayout.addComponent(caption);
		headerLayout.setExpandRatio(caption, 1.0f);
		
		// buttonChangePassword
		buttonChangePassword = new Button();
		buttonChangePassword.setCaption("Change Password");
		buttonChangePassword.setImmediate(true);
		buttonChangePassword.setWidth("-1px");
		buttonChangePassword.setHeight("-1px");
		headerLayout.addComponent(buttonChangePassword);
		headerLayout.setComponentAlignment(buttonChangePassword, new Alignment(
				6));
		
		// buttonLogout
		buttonLogout = new Button();
		buttonLogout.setCaption("Log Out");
		buttonLogout.setImmediate(true);
		buttonLogout.setWidth("-1px");
		buttonLogout.setHeight("-1px");
		headerLayout.addComponent(buttonLogout);
		headerLayout.setComponentAlignment(buttonLogout, new Alignment(6));
		
		return headerLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildBodyLayout() {
		// common part: create layout
		bodyLayout = new HorizontalLayout();
		bodyLayout.setImmediate(false);
		bodyLayout.setWidth("100.0%");
		bodyLayout.setHeight("100.0%");
		bodyLayout.setMargin(true);
		bodyLayout.setSpacing(true);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("100.0%");
		label_1.setHeight("100.0%");
		label_1.setValue("Lorem ipsum dolor sit amet...");
		bodyLayout.addComponent(label_1);
		bodyLayout.setExpandRatio(label_1, 1.0f);
		
		return bodyLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildFooterLayout() {
		// common part: create layout
		footerLayout = new HorizontalLayout();
		footerLayout.setImmediate(false);
		footerLayout.setWidth("100.0%");
		footerLayout.setHeight("-1px");
		footerLayout.setMargin(false);
		
		// copyRight
		copyRight = new Label();
		copyRight.setImmediate(false);
		copyRight.setWidth("-1px");
		copyRight.setHeight("-1px");
		copyRight.setValue("Copyright to Mladen Čikara");
		footerLayout.addComponent(copyRight);
		footerLayout.setComponentAlignment(copyRight, new Alignment(20));
		
		return footerLayout;
	}

}
